schemadotorg_devel.settings:
  type: config_object
  label: 'Schema.org Devel settings'
  mapping:
    generate_values:
      type: sequence
      label: 'Schema.org generate values'
      sequence:
        type: mapping
        label: 'Schema.org generate values'
        mapping:
          values:
            type: sequence
            label: Values
            sequence:
              type: text
              label: Value
          string:
            type: integer
            label: 'String length'
          name:
            type: integer
            label: 'Name length'
          machine_name:
            type: integer
            label: 'Machine name length'
          word:
            type: integer
            label: 'Word length'
          words:
            type: integer
            label: 'Word count'
          sentences:
            type: integer
            label: 'Sentences minimum word count'
          paragraphs:
            type: integer
            label: 'Paragraph count'
