name: vtstudentsfirst
recipe: drupal10
config:
  webroot: web
  php: '8.3'
  composer_version: '2'
  database: postgres:15

proxy:
  appserver:
    - vtstudentsfirst.lndo.site

services:
  appserver:
    type: php:8.3
    webroot: public_html
    via: apache
    overrides:
      extra_hosts:
        - 'host.docker.internal:172.17.0.1'
      environment:
        DRUSH_OPTIONS_URI: "https://vtstudentsfirst.lndo.site"

  database:
    type: postgres:15
    creds:
      database: drupal
      user: drupal
      password: drupal
    config:
      extensions:
        - postgis

tooling:
  composer:
    service: appserver
  drush:
    service: appserver
