<?php

/**
 * @file
 * Allows Allowed Formats to be used to create Schema.org relationships.
 */

declare(strict_types=1);

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_schemadotorg_property_field_alter().
 */
function schemadotorg_allowed_formats_schemadotorg_property_field_alter(
  string $schema_type,
  string $schema_property,
  array &$field_storage_values,
  array &$field_values,
  ?string &$widget_id,
  array &$widget_settings,
  ?string &$formatter_id,
  array &$formatter_settings,
): void {
  /** @var \Drupal\schemadotorg_allowed_formats\SchemaDotOrgAllowedFormatsManagerInterface $schema_allowed_formats_manager */
  $schema_allowed_formats_manager = \Drupal::service('schemadotorg_allowed_formats.manager');
  $schema_allowed_formats_manager->propertyFieldAlter(
    $schema_type,
    $schema_property,
    $field_storage_values,
    $field_values,
    $widget_id,
    $widget_settings,
    $formatter_id,
    $formatter_settings
  );
}

/* ************************************************************************** */
// Schema.org properties settings form.
/* ************************************************************************** */

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see \Drupal\schemadotorg\Form\SchemaDotOrgSettingsFormBase::afterBuildDetails
 * @see \Drupal\schemadotorg\Form\SchemaDotOrgSettingsFormBase::formAlter
 */
function schemadotorg_allowed_formats_form_schemadotorg_properties_settings_form_alter(array &$form, FormStateInterface $form_state): void {
  $allowed_formats_options = [];
  foreach (filter_formats() as $format) {
    $allowed_formats_options[$format->id()] = $format->label();
  }

  $form['schemadotorg_allowed_formats'] = [
    '#type' => 'details',
    '#title' => t('Allowed formats settings'),
  ];
  $form['schemadotorg_allowed_formats']['default_allowed_formats'] = [
    '#type' => 'schemadotorg_settings',
    '#title' => t('Default allowed formats'),
    '#description' => t('Enter allowed formats for specific entity type/bundle or Schema.org type/properties.'),
    '#description_link' => 'properties',
    '#example' => '
schemaProperty:
  - full_html
  - basic_html
SchemaType--propertyName:
  - full_html
  - basic_html
entity_type_id:
  - full_html
  - basic_html
',
  ];
  $form['schemadotorg_allowed_formats']['default_hide_help'] = [
    '#type' => 'checkbox',
    '#title' => t('Hide the help link <em>About text formats</em>.'),
    '#description' => t('If checked, the help link will be hidden when text format widgets are created.'),
  ];
  $form['schemadotorg_allowed_formats']['default_hide_guidelines'] = [
    '#type' => 'checkbox',
    '#title' => t('Hide text format guidelines.'),
    '#description' => t('If checked, the text format guidelines will be hidden when text format widgets are created.'),
  ];
}
