<?php

/**
 * @file
 * Set allowed values for list (options) fields.
 */

declare(strict_types=1);

use Drupal\Core\Field\FieldItemInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Language\LanguageManager;
use Drupal\Core\Locale\CountryManager;
use Drupal\Core\Render\BubbleableMetadata;

/**
 * Implements hook_schemadotorg_property_field_type_alter().
 */
function schemadotorg_options_schemadotorg_property_field_type_alter(array &$field_types, string $entity_type_id, string $schema_type, string $schema_property): void {
  /** @var \Drupal\schemadotorg_options\SchemaDotOrgOptionsManagerInterface $schemadotorg_options_manager */
  $schemadotorg_options_manager = \Drupal::service('schemadotorg_options.manager');
  $schemadotorg_options_manager->propertyFieldTypeAlter($field_types, $entity_type_id, $schema_type, $schema_property);
}

/**
 * Implements hook_schemadotorg_property_field_alter().
 */
function schemadotorg_options_schemadotorg_property_field_alter(
  string $schema_type,
  string $schema_property,
  array &$field_storage_values,
  array &$field_values,
  ?string &$widget_id,
  array &$widget_settings,
  ?string &$formatter_id,
  array &$formatter_settings,
): void {
  /** @var \Drupal\schemadotorg_options\SchemaDotOrgOptionsManagerInterface $schemadotorg_options_manager */
  $schemadotorg_options_manager = \Drupal::service('schemadotorg_options.manager');
  $schemadotorg_options_manager->propertyFieldAlter(
    $schema_type,
    $schema_property,
    $field_storage_values,
    $field_values,
    $widget_id,
    $widget_settings,
    $formatter_id,
    $formatter_settings
  );
}

/**
 * Implements hook_schemadotorg_jsonld_schema_property_alter().
 */
function schemadotorg_options_schemadotorg_jsonld_schema_property_alter(mixed &$value, FieldItemInterface $item, BubbleableMetadata $bubbleable_metadata): void {
  /** @var \Drupal\schemadotorg_options\SchemaDotOrgOptionsJsonLdManagerInterface $schemadotorg_options_jsonld_manager */
  $schemadotorg_options_jsonld_manager = \Drupal::service('schemadotorg_options.jsonld_manager');
  $schemadotorg_options_jsonld_manager->schemaPropertyAlter($value, $item, $bubbleable_metadata);
}

/* ************************************************************************** */
// Schema.org properties settings form.
/* ************************************************************************** */

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see \Drupal\schemadotorg\Form\SchemaDotOrgSettingsFormBase::afterBuildDetails
 * @see \Drupal\schemadotorg\Form\SchemaDotOrgSettingsFormBase::formAlter
 */
function schemadotorg_options_form_schemadotorg_properties_settings_form_alter(array &$form, FormStateInterface $form_state): void {
  $form['schemadotorg_options'] = [
    '#type' => 'details',
    '#title' => t('Options settings'),
  ];
  $form['schemadotorg_options']['schema_property_allowed_values'] = [
    '#type' => 'schemadotorg_settings',
    '#title' => t('Schema.org property allowed values'),
    '#description' => t('Enter Schema.org types and properties with allowed values.'),
    '#description_link' => 'properties',
    '#example' => '
propertyName:
  option01: Option 1
  option02: Options 2
SchemaType--propertyName:
  option01: Option 1
  option02: Options 2
',
  ];
  $form['schemadotorg_options']['schema_property_allowed_values_remove'] = [
    '#type' => 'schemadotorg_settings',
    '#title' => t('Schema.org property allowed values prefixes/suffixes'),
    '#description' => t('Enter Schema.org properties with allowed values prefixes and suffixes that should be removed.'),
    '#description_link' => 'properties',
    '#example' => 'propertyName: suffix',
  ];
  $form['schemadotorg_options']['allowed_value_aliases'] = [
    '#type' => 'schemadotorg_settings',
    '#title' => t('Allowed value (enumeration) aliases'),
    '#description' => t('Enter Schema.org Enumeration followed by its aliases for the Schema.org JSON-LD. This allows for more readable values (i.e. snake_case values) for Enumeration values.'),
    '#description_link' => 'properties',
    '#example' => "
MixedEventAttendanceMode: mixes
eventAttendanceMode--OfflineEventAttendanceMode: offline
Event--eventAttendanceMode--OnlineEventAttendanceMode: online
",
  ];
  $form['schemadotorg_options']['jsonld_text'] = [
    '#type' => 'schemadotorg_settings',
    '#title' => t('Schema.org properties that display allowed value text in the Schema.org JSON-LD'),
    '#description' => t('Enter the Schema.org properties that should return the (translated) text for an allowed value in the Schema.org JSON-LD.')
      . ' '
      . t("Enter '- Thing' to convert all Schema.org properties to use the (translated) text for an allowed value in the Schema.org JSON-LD."),
    '#description_link' => 'properties',
    '#example' => "
- SchemaType--propertyName
- SchemaType
- propertyName
",
    '#access' => \Drupal::moduleHandler()->moduleExists('schemadotorg_jsonld'),
  ];
  $form['schemadotorg_options']['jsonld_uris'] = [
    '#type' => 'schemadotorg_settings',
    '#title' => t('URIs for allowed values in the Schema.org JSON-LD'),
    '#description' => t('Enter URIs to be used in the Schema.org JSON-LD for an allowed value.')
      .
      ' ' . t('The JSON-LD URIs allows internal option machine names to mapped to a well known URL from Wikipedia or Wikidata'),
    '#description_link' => 'properties',
    '#example' => "
# Patterns
SchemaType--propertyName--allowed_value: 'https://www.wikidata.org/wiki/Q0000'
propertyName--allowed_value: 'https://www.wikidata.org/wiki/Q0000'
allowed_value: 'https://www.wikidata.org/wiki/Q0000'
# Examples
warning: 'https://www.wikidata.org/wiki/Q1759104'
emergency: 'https://www.wikidata.org/wiki/Q5070802'
error: 'https://www.wikidata.org/wiki/Q29485'
information: 'https://www.wikidata.org/wiki/Q11028'
condition: 'https://www.wikidata.org/wiki/Q813912'
",
    '#access' => \Drupal::moduleHandler()->moduleExists('schemadotorg_jsonld'),
  ];
  $form['schemadotorg_options']['use_snake_case'] = [
    '#type' => 'checkbox',
    '#title' => t('Use snake case for allowed (enumeration) values'),
    '#description' => t('If checked, allowed (enumeration) values will automatically be converted to snake_case.'),
  ];
}

/* ************************************************************************** */
// Allowed values function callbacks.
/* ************************************************************************** */

/**
 * HOOK_options_allowed_values_SCHEMA_TYPE()
 */
function schemadotorg_options_allowed_values_country(): array {
  return CountryManager::getStandardList();
}

/**
 * HOOK_options_allowed_values_SCHEMA_TYPE()
 */
function schemadotorg_options_allowed_values_language(): array {
  $languages = LanguageManager::getStandardLanguageList();
  unset($languages['en-x-simple']);
  $allowed_values = [];
  foreach ($languages as $language) {
    $allowed_values[$language[0]] = $language[0];
  }
  return $allowed_values;
}
