<?php

/**
 * @file
 * Assists with creating and mapping taxonomy vocabularies and terms.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Field\FieldItemInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\schemadotorg\SchemaDotOrgMappingInterface;

/**
 * Implements hook_schemadotorg_jsonld_schema_property_alter().
 */
function schemadotorg_taxonomy_schemadotorg_jsonld_schema_property_alter(mixed &$value, FieldItemInterface $item, BubbleableMetadata $bubbleable_metadata): void {
  /** @var \Drupal\schemadotorg_taxonomy\SchemaDotOrgTaxonomyJsonLdManagerInterface $schemadotorg_taxonomy_jsonld_manager */
  $schemadotorg_taxonomy_jsonld_manager = \Drupal::service('schemadotorg_taxonomy.jsonld_manager');
  $schemadotorg_taxonomy_jsonld_manager->schemaPropertyAlter($value, $item, $bubbleable_metadata);
}

/**
 * Implements hook_schemadotorg_jsonld_schema_type_entity_load().
 */
function schemadotorg_taxonomy_schemadotorg_jsonld_schema_type_entity_load(array &$data, EntityInterface $entity, ?SchemaDotOrgMappingInterface $mapping, BubbleableMetadata $bubbleable_metadata): void {
  /** @var \Drupal\schemadotorg_taxonomy\SchemaDotOrgTaxonomyJsonLdManagerInterface $schemadotorg_taxonomy_jsonld_manager */
  $schemadotorg_taxonomy_jsonld_manager = \Drupal::service('schemadotorg_taxonomy.jsonld_manager');
  $schemadotorg_taxonomy_jsonld_manager->schemaTypeEntityLoad($data, $entity, $mapping, $bubbleable_metadata);
}

/**
 * Implements hook_schemadotorg_jsonld_schema_type_entity_alter().
 */
function schemadotorg_taxonomy_schemadotorg_jsonld_schema_type_entity_alter(array &$data, EntityInterface $entity, ?SchemaDotOrgMappingInterface $mapping, BubbleableMetadata $bubbleable_metadata): void {
  /** @var \Drupal\schemadotorg_taxonomy\SchemaDotOrgTaxonomyJsonLdManagerInterface $schemadotorg_taxonomy_jsonld_manager */
  $schemadotorg_taxonomy_jsonld_manager = \Drupal::service('schemadotorg_taxonomy.jsonld_manager');
  $schemadotorg_taxonomy_jsonld_manager->schemaTypeEntityAlter($data, $entity, $mapping, $bubbleable_metadata);
}

/**
 * Implements hook_preprocess_block().
 */
function schemadotorg_taxonomy_preprocess_block(array &$variables): void {
  /** @var \Drupal\schemadotorg_taxonomy\SchemaDotOrgTaxonomyJsonLdManagerInterface $schemadotorg_taxonomy_jsonld_manager */
  $schemadotorg_taxonomy_jsonld_manager = \Drupal::service('schemadotorg_taxonomy.jsonld_manager');
  $schemadotorg_taxonomy_jsonld_manager->preprocessBlock($variables);
}

/* ************************************************************************** */
// Default type vocabulary.
/* ************************************************************************** */

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function schemadotorg_taxonomy_schemadotorg_mapping_insert(SchemaDotOrgMappingInterface $mapping): void {
  /** @var \Drupal\schemadotorg_taxonomy\SchemaDotOrgTaxonomyDefaultVocabularyManagerInterface $schemadotorg_taxonomy_default_vocabulary_manager */
  $schemadotorg_taxonomy_default_vocabulary_manager = \Drupal::service('schemadotorg_taxonomy.default_vocabulary_manager');
  $schemadotorg_taxonomy_default_vocabulary_manager->mappingInsert($mapping);
}

/* ************************************************************************** */
// Default property vocabulary.
/* ************************************************************************** */

/**
 * Implements hook_schemadotorg_property_field_type_alter().
 */
function schemadotorg_taxonomy_schemadotorg_property_field_type_alter(array &$field_types, string $entity_type_id, string $schema_type, string $schema_property): void {
  /** @var \Drupal\schemadotorg_taxonomy\SchemaDotOrgTaxonomyPropertyVocabularyManagerInterface $schemadotorg_taxonomy_property_vocabulary_manager */
  $schemadotorg_taxonomy_property_vocabulary_manager = \Drupal::service('schemadotorg_taxonomy.property_vocabulary_manager');
  $schemadotorg_taxonomy_property_vocabulary_manager->propertyFieldTypeAlter($field_types, $schema_type, $schema_property);
}

/**
 * Implements hook_schemadotorg_property_field_alter().
 */
function schemadotorg_taxonomy_schemadotorg_property_field_alter(
  string $schema_type,
  string $schema_property,
  array &$field_storage_values,
  array &$field_values,
  ?string &$widget_id,
  array &$widget_settings,
  ?string &$formatter_id,
  array &$formatter_settings,
): void {
  /** @var \Drupal\schemadotorg_taxonomy\SchemaDotOrgTaxonomyPropertyVocabularyManagerInterface $schemadotorg_taxonomy_property_vocabulary_manager */
  $schemadotorg_taxonomy_property_vocabulary_manager = \Drupal::service('schemadotorg_taxonomy.property_vocabulary_manager');
  $schemadotorg_taxonomy_property_vocabulary_manager->propertyFieldAlter(
    $schema_type,
    $schema_property,
    $field_storage_values,
    $field_values,
    $widget_id,
    $widget_settings,
    $formatter_id,
    $formatter_settings
  );
}

/* ************************************************************************** */
// Schema.org types settings form.
/* ************************************************************************** */

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see \Drupal\schemadotorg\Form\SchemaDotOrgSettingsFormBase::afterBuildDetails
 * @see \Drupal\schemadotorg\Form\SchemaDotOrgSettingsFormBase::formAlter
 */
function schemadotorg_taxonomy_form_schemadotorg_types_settings_form_alter(array &$form, FormStateInterface $form_state): void {
  $form['schemadotorg_taxonomy'] = [
    '#type' => 'details',
    '#title' => t('Taxonomy settings'),
  ];
  $form['schemadotorg_taxonomy']['default_vocabularies'] = [
    '#type' => 'schemadotorg_settings',
    '#title' => t('Default vocabularies'),
    '#description' => t('Enter default vocabularies that will be added to every Schema.org content type.'),
    '#example' => "
unique_name:
  id: vocabulary_id
  label: Vocabulary name
  description: Vocabulary description goes here
  field_name: field_unique_name
  group: group_name
  auto_create: true
  unlimited: true
  required: true
  widget_id: widget_id
  widget_settings: {  }
  formatter_id: formatter_id
  formatter_settings: {  }
  schema_types:
   - SchemaType
   - entity_type_id--bundle
   - bundle
   - '!SchemaType'
   - '!entity_type_id--bundle'
   - '!bundle'

",
  ];

  $form['schemadotorg_taxonomy']['apply'] = [];
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see \Drupal\schemadotorg\Form\SchemaDotOrgSettingsFormBase::afterBuildDetails
 * @see \Drupal\schemadotorg\Form\SchemaDotOrgSettingsFormBase::formAlter
 */
function schemadotorg_taxonomy_form_schemadotorg_properties_settings_form_alter(array &$form, FormStateInterface $form_state): void {
  $form['schemadotorg_taxonomy'] = [
    '#type' => 'details',
    '#title' => t('Taxonomy settings'),
  ];
  $form['schemadotorg_taxonomy']['schema_property_vocabularies'] = [
    '#type' => 'schemadotorg_settings',
    '#title' => t('Default vocabulary properties'),
    '#description' => t('Enter Schema.org properties that should be mapped to a vocabulary.')
    . '<br/>'
    . t('If the mapped vocabulary does exist it will be created when the Schema.org property mapping is created.')
    . ' '
    . t('Omitting Schema.org types will apply the default vocabulary to all content types.'),
    '#description_link' => 'properties',
    '#example' => '
propertyName:
  id: vocabulary_id
  label: Vocabulary name
  description: Vocabulary description goes here
  auto_create: true
  schema_types:
    - SchemaType
    - entity_type_id--SchemaType
    - entity_type_id--bundle
',
  ];
}
