schemadotorg_options.settings:
  type: config_object
  label: 'Schema.org Options settings'
  mapping:
    schema_property_allowed_values:
      type: sequence
      label: 'Schema.org property'
      sequence:
        type: sequence
        label: 'Allowed values'
        sequence:
          type: text
          label: Text
    schema_property_allowed_values_remove:
      type: sequence
      label: 'Schema.org property allowed values remove prefixes/suffixes'
      sequence:
        type: text
        label: 'Schema.org property allowed values remove prefix/suffix'
    allowed_value_aliases:
      type: sequence
      label: 'Allowed value aliases'
      sequence:
        type: text
        label: 'Allowed value alias'
    jsonld_text:
      type: sequence
      label: 'JSON-LD text'
      sequence:
        type: string
        label: 'JSON-LD text'
    jsonld_uris:
      type: sequence
      label: 'JSON-LD URIs'
      sequence:
        type: uri
        label: 'JSON-LD URI'
    use_snake_case:
      type: boolean
      label: 'Use snake case for allowed (enumeration) values'
