<?php

/**
 * @file
 * Allows additional Schema.org mappings to applied to a Schema.org mapping.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Field\FieldItemInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\schemadotorg\SchemaDotOrgMappingInterface;

/**
 * Implements hook_schemadotorg_mapping_defaults_alter().
 */
function schemadotorg_additional_mappings_schemadotorg_mapping_defaults_alter(array &$defaults, string $entity_type_id, ?string $bundle, string $schema_type): void {
  /** @var \Drupal\schemadotorg_additional_mappings\SchemaDotOrgAdditionalMappingsManagerInterface $schemadotorg_additional_mappings_manager */
  $schemadotorg_additional_mappings_manager = \Drupal::service('schemadotorg_additional_mappings.manager');
  $schemadotorg_additional_mappings_manager->mappingDefaultsAlter($defaults, $entity_type_id, $bundle, $schema_type);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function schemadotorg_additional_mappings_form_schemadotorg_mapping_form_alter(array &$form, FormStateInterface &$form_state): void {
  /** @var \Drupal\schemadotorg_additional_mappings\SchemaDotOrgAdditionalMappingsManagerInterface $schemadotorg_additional_mappings_manager */
  $schemadotorg_additional_mappings_manager = \Drupal::service('schemadotorg_additional_mappings.manager');
  $schemadotorg_additional_mappings_manager->mappingFormAlter($form, $form_state);
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function schemadotorg_additional_mappings_schemadotorg_mapping_presave(SchemaDotOrgMappingInterface $mapping): void {
  /** @var \Drupal\schemadotorg_additional_mappings\SchemaDotOrgAdditionalMappingsManagerInterface $schemadotorg_additional_mappings_manager */
  $schemadotorg_additional_mappings_manager = \Drupal::service('schemadotorg_additional_mappings.manager');
  $schemadotorg_additional_mappings_manager->mappingPreSave($mapping);
}

/**
 * Implements hook_ENTITY_TYPE_postsave().
 */
function schemadotorg_additional_mappings_schemadotorg_mapping_postsave(SchemaDotOrgMappingInterface $mapping): void {
  /** @var \Drupal\schemadotorg_additional_mappings\SchemaDotOrgAdditionalMappingsManagerInterface $schemadotorg_additional_mappings_manager */
  $schemadotorg_additional_mappings_manager = \Drupal::service('schemadotorg_additional_mappings.manager');
  $schemadotorg_additional_mappings_manager->mappingPostSave($mapping);
}

/**
 * Implements hook_schemadotorg_jsonld_schema_type_entity_alter().
 */
function schemadotorg_additional_mappings_schemadotorg_jsonld_schema_type_entity_alter(array &$data, EntityInterface $entity, ?SchemaDotOrgMappingInterface $mapping, BubbleableMetadata $bubbleable_metadata): void {
  /** @var \Drupal\schemadotorg_additional_mappings\SchemaDotOrgAdditionalMappingsJsonLdManagerInterface $schemadotorg_additional_mappings_jsonld_manager */
  $schemadotorg_additional_mappings_jsonld_manager = \Drupal::service('schemadotorg_additional_mappings.jsonld_manager');
  $schemadotorg_additional_mappings_jsonld_manager->entityAlter($data, $entity, $mapping, $bubbleable_metadata);
}

/**
 * Implements hook_schemadotorg_jsonld_alter().
 */
function schemadotorg_additional_mappings_schemadotorg_jsonld_alter(array &$data, RouteMatchInterface $route_match, BubbleableMetadata $bubbleable_metadata): void {
  /** @var \Drupal\schemadotorg_additional_mappings\SchemaDotOrgAdditionalMappingsJsonLdManagerInterface $schemadotorg_additional_mappings_jsonld_manager */
  $schemadotorg_additional_mappings_jsonld_manager = \Drupal::service('schemadotorg_additional_mappings.jsonld_manager');
  $schemadotorg_additional_mappings_jsonld_manager->alter($data, $route_match, $bubbleable_metadata);
}

/**
 * Implements hook_schemadotorg_jsonld_schema_property_alter().
 */
function schemadotorg_additional_mappings_schemadotorg_jsonld_schema_property_alter(mixed &$value, FieldItemInterface $item, BubbleableMetadata $bubbleable_metadata): void {
  /** @var \Drupal\schemadotorg_additional_mappings\SchemaDotOrgAdditionalMappingsJsonLdManagerInterface $schemadotorg_additional_mappings_jsonld_manager */
  $schemadotorg_additional_mappings_jsonld_manager = \Drupal::service('schemadotorg_additional_mappings.jsonld_manager');
  $schemadotorg_additional_mappings_jsonld_manager->schemaPropertyAlter($value, $item, $bubbleable_metadata);
}

/* ************************************************************************** */
// Schema.org types settings form.
/* ************************************************************************** */

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see \Drupal\schemadotorg\Form\SchemaDotOrgSettingsFormBase::afterBuildDetails
 * @see \Drupal\schemadotorg\Form\SchemaDotOrgSettingsFormBase::formAlter
 */
function schemadotorg_additional_mappings_form_schemadotorg_types_settings_form_alter(array &$form, FormStateInterface $form_state): void {
  $form['schemadotorg_additional_mappings'] = [
    '#type' => 'details',
    '#title' => t('Additional mappings settings'),
  ];
  $form['schemadotorg_additional_mappings']['default_additional_mappings'] = [
    '#type' => 'schemadotorg_settings',
    '#title' => t('Default additional Schema.org mappings'),
    '#description' => t('Enter the additional Schema.org mappings for Schema.org mapping type.'),
    '#description_link' => 'types',
    '#example' => "
node--MainSchemaType:
  - AdditionalSchemaType
",
  ];
  $form['schemadotorg_additional_mappings']['default_properties'] = [
    '#type' => 'schemadotorg_settings',
    '#title' => t('Default additional Schema.org mappings properties'),
    '#rows' => 10,
    '#description' => t('Enter default properties for  additional Schema.org mappings types.'),
    '#description_link' => 'types',
    '#example' => "
SchemaType:
  - '!removedPropertyName01'
  - propertyName01
  - propertyName02
  - propertyName03
MainSchemaType--AdditionalSchemaType:
  - '!removedPropertyName01'
  - propertyName01
  - propertyName02
  - propertyName03
",
  ];
}
