<?php

/**
 * @file
 * Adds field validation/constraint rules to Schema.org properties.
 */

declare(strict_types=1);

use Drupal\Core\Field\FieldConfigInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function schemadotorg_field_validation_field_config_insert(FieldConfigInterface $field_config): void {
  /** @var \Drupal\schemadotorg_field_validation\SchemaDotOrgFieldValidationManagerInterface $schemadotorg_field_validation_manager */
  $schemadotorg_field_validation_manager = \Drupal::service('schemadotorg_field_validation.manager');
  $schemadotorg_field_validation_manager->fieldConfigInsert($field_config);
}

/* ************************************************************************** */
// Schema.org properties settings form.
/* ************************************************************************** */

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see \Drupal\schemadotorg\Form\SchemaDotOrgSettingsFormBase::afterBuildDetails
 * @see \Drupal\schemadotorg\Form\SchemaDotOrgSettingsFormBase::formAlter
 */
function schemadotorg_field_validation_form_schemadotorg_properties_settings_form_alter(array &$form, FormStateInterface $form_state): void {
  $form['schemadotorg_field_validation'] = [
    '#type' => 'details',
    '#title' => t('Field validation settings'),
  ];
  $form['schemadotorg_field_validation']['rules'] = [
    '#type' => 'schemadotorg_settings',
    '#title' => t('Field validation rules'),
    '#description' => t('Enter field validation rules for Schema.org types and fields.'),
    '#example' => "
propertyName:
  pattern: '/^\d{10]$/'
  message: 'Property name must be a 10-digit number.'
",
  ];
}
