<?php

/**
 * @file
 * Allows an Office hours field to be used to create OpeningHoursSpecification.
 */

declare(strict_types=1);

use Drupal\Core\Field\FieldItemInterface;
use Drupal\Core\Render\BubbleableMetadata;

/**
 * Implements hook_schemadotorg_property_field_alter().
 */
function schemadotorg_office_hours_schemadotorg_property_field_alter(
  string $schema_type,
  string $schema_property,
  array &$field_storage_values,
  array &$field_values,
  ?string &$widget_id,
  array &$widget_settings,
  ?string &$formatter_id,
  array &$formatter_settings,
): void {
  /** @var \Drupal\schemadotorg_office_hours\SchemaDotOrgOfficeHoursManagerInterface $schemadotorg_office_hours_manager */
  $schemadotorg_office_hours_manager = \Drupal::service('schemadotorg_office_hours.manager');
  $schemadotorg_office_hours_manager->propertyFieldAlter(
    $schema_type,
    $schema_property,
    $field_storage_values,
    $field_values,
    $widget_id,
    $widget_settings,
    $formatter_id,
    $formatter_settings
  );
}

/**
 * Implements hook_schemadotorg_jsonld_schema_property_alter().
 */
function schemadotorg_office_hours_schemadotorg_jsonld_schema_property_alter(mixed &$value, FieldItemInterface $item, BubbleableMetadata $bubbleable_metadata): void {
  /** @var \Drupal\schemadotorg_office_hours\SchemaDotOrgOfficeHoursJsonLdManagerInterface $schemadotorg_office_hours_jsonld_manager */
  $schemadotorg_office_hours_jsonld_manager = \Drupal::service('schemadotorg_office_hours.jsonld_manager');
  $schemadotorg_office_hours_jsonld_manager->schemaPropertyAlter($value, $item, $bubbleable_metadata);
}
