<?php

/**
 * @file
 * Primary module hooks for Global Volcanism module.
 */

/**
 * Implements hook_0().
 */
/**
 * Implements hook_preprocess_HOOK() for html.twig.
 */
function global_volcanism_preprocess_html(array &$variables) {
  // Grab the service directly from the container
  /** @var \Drupal\global_volcanism\Services\VolcanoesService $svc */
//  $svc = \Drupal::service('global_volcanism.VolcanoesService');
//
//  // Fetch data
//  $latest_activity = $svc->getLatestActivity();
//
//  ray($latest_activity);
//
//  // Expose to Twig
//  $variables['latest_volcano_activity'] = $latest_activity;
//  $storage = \Drupal::entityTypeManager()->getStorage('si_mapping_types');
//
//  ray($storage);
}
