<?php

/**
 * @file
 * Allows Smart Dates to be used to create Schema.org relationships.
 */

declare(strict_types=1);

use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Render\BubbleableMetadata;

/**
 * Implements hook_schemadotorg_property_field_alter().
 */
function schemadotorg_smart_date_schemadotorg_property_field_alter(
  string $schema_type,
  string $schema_property,
  array &$field_storage_values,
  array &$field_values,
  ?string &$widget_id,
  array &$widget_settings,
  ?string &$formatter_id,
  array &$formatter_settings,
): void {
  /** @var \Drupal\schemadotorg_smart_date\SchemaDotOrgSmartDateManager $schemadotorg_smart_date_manager */
  $schemadotorg_smart_date_manager = \Drupal::service('schemadotorg_smart_date.manager');
  $schemadotorg_smart_date_manager->propertyFieldAlter(
    $schema_type,
    $schema_property,
    $field_storage_values,
    $field_values,
    $widget_id,
    $widget_settings,
    $formatter_id,
    $formatter_settings
  );
}

/**
 * Implements hook_schemadotorg_jsonld_schema_type_field_alter().
 */
function schemadotorg_smart_date_schemadotorg_jsonld_schema_type_field_alter(array &$data, FieldItemListInterface $items, BubbleableMetadata $bubbleable_metadata): void {
  /** @var \Drupal\schemadotorg_smart_date\SchemaDotOrgSmartDateJsonLdManagerInterface $jsonld_manager */
  $jsonld_manager = \Drupal::service('schemadotorg_smart_date.jsonld_manager');
  $jsonld_manager->alterProperties($data, $items, $bubbleable_metadata);
}
