<?php

/**
 * @file
 * Automatically enables content moderation Schema.org types.
 */

declare(strict_types=1);

use Drupal\Core\Form\FormStateInterface;
use Drupal\schemadotorg\SchemaDotOrgMappingInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function schemadotorg_content_moderation_schemadotorg_mapping_insert(SchemaDotOrgMappingInterface $mapping): void {
  /** @var \Drupal\schemadotorg_content_moderation\SchemaDotOrgContentModerationManagerInterface $schemadotorg_content_moderation_manager */
  $schemadotorg_content_moderation_manager = \Drupal::service('schemadotorg_content_moderation.manager');
  $schemadotorg_content_moderation_manager->mappingInsert($mapping);
}

/* ************************************************************************** */
// Schema.org types settings form.
/* ************************************************************************** */

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see \Drupal\schemadotorg\Form\SchemaDotOrgSettingsFormBase::afterBuildDetails
 * @see \Drupal\schemadotorg\Form\SchemaDotOrgSettingsFormBase::formAlter
 */
function schemadotorg_content_moderation_form_schemadotorg_types_settings_form_alter(array &$form, FormStateInterface $form_state): void {
  $form['schemadotorg_content_moderation'] = [
    '#type' => 'details',
    '#title' => t('Content moderation settings'),
  ];
  $form['schemadotorg_content_moderation']['default_workflows'] = [
    '#type' => 'schemadotorg_settings',
    '#title' => t('Default content moderation workflows'),
    '#description' => t('Enter the default content moderation workflow per entity type and Schema.org type. Set to <em>null</em> to not set a workflow for a Schema.org type.'),
    '#example' => '
entity_type: workflow_id
entity_type--SchemaType01: workflow_id
entity_type--SchemaType02: null',
  ];

  $form['schemadotorg_content_moderation']['apply'] = [];
}
