<?php

/**
 * @file
 * Integrates content blocks with the Schema.org Blueprints module.
 */

declare(strict_types=1);

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\schemadotorg\Entity\SchemaDotOrgMapping;

/**
 * Implements hook_schemadotorg_jsonld().
 */
function schemadotorg_block_content_schemadotorg_jsonld(RouteMatchInterface $route_match, BubbleableMetadata $bubbleable_metadata): ?array {
  /** @var \Drupal\schemadotorg_block_content\SchemaDotOrgBlockContentJsonLdManagerInterface $schemadotorg_block_content_jsonld_manager */
  $schemadotorg_block_content_jsonld_manager = \Drupal::service('schemadotorg_block_content.jsonld_manager');
  return $schemadotorg_block_content_jsonld_manager->jsonLd($route_match, $bubbleable_metadata);
}

/**
 * Implements hook_form_alter().
 */
function schemadotorg_block_content_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  // Alert block content form that is mapped to Schema.org type.
  if (!str_starts_with($form_id, 'block_content_')
    || !preg_match('/^block_content_(.*?)_(edit_form|form)$/', $form_id, $matches)) {
    return;
  }

  $bundle = $matches[1];
  $mapping = SchemaDotOrgMapping::load('block_content.' . $bundle);
  if (!$mapping) {
    return;
  }

  // Ensure that the block content form's vertical tabs and submit button
  // are always last.
  $form['advanced']['#weight'] = 250;
  $form['actions']['#weight'] = 251;
}
