<?php

/**
 * @file
 * Allows an Geolocation field to be used to create GeoCoordinates.
 */

declare(strict_types=1);

use Drupal\Core\Field\FieldItemInterface;
use Drupal\Core\Render\BubbleableMetadata;

/**
 * Implements hook_schemadotorg_property_field_alter().
 */
function schemadotorg_geolocation_schemadotorg_property_field_alter(
  string $schema_type,
  string $schema_property,
  array &$field_storage_values,
  array &$field_values,
  ?string &$widget_id,
  array &$widget_settings,
  ?string &$formatter_id,
  array &$formatter_settings,
): void {
  /** @var \Drupal\schemadotorg_geolocation\SchemaDotOrgGeolocationManagerInterface $schemadotorg_geolocation_manager */
  $schemadotorg_geolocation_manager = \Drupal::service('schemadotorg_geolocation.manager');
  $schemadotorg_geolocation_manager->propertyFieldAlter(
    $schema_type,
    $schema_property,
    $field_storage_values,
    $field_values,
    $widget_id,
    $widget_settings,
    $formatter_id,
    $formatter_settings
  );
}

/**
 * Implements hook_schemadotorg_jsonld_schema_property_alter().
 */
function schemadotorg_geolocation_schemadotorg_jsonld_schema_property_alter(mixed &$value, FieldItemInterface $item, BubbleableMetadata $bubbleable_metadata): void {
  /** @var \Drupal\schemadotorg_geolocation\SchemaDotOrgGeolocationJsonLdManagerInterface $schemadotorg_geolocation_jsonld_manager */
  $schemadotorg_geolocation_jsonld_manager = \Drupal::service('schemadotorg_geolocation.jsonld_manager');
  $schemadotorg_geolocation_jsonld_manager->schemaPropertyAlter($value, $item, $bubbleable_metadata);
}
